config/routes.rb
Rails.application.routes.draw do
  root 'posts#homepage'

  resources :categories
  resources :authors
  resources :posts do
    collection do
      get 'homepage'
      post 'homepage'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates_presence_of :name

  has_many :posts
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  belongs_to :category

  scope :recents, ->{where("created_at > ?", (Time.now - 40.days).beginning_of_day)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :age)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:description)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def homepage
    @posts = Post.recents.order("created_at desc")
    @posts = @posts.where(category: params[:category_id]) unless params[:category_id].blank?
    @posts = @posts.where("UPPER(text) like ?" , "%#{params[:search_term].to_s.upcase}%") unless params[:search_term].blank?
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:text, :subject, :title, :author_id, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(title, path)
    classValue = current_page?(path) ? 'active' : ''
    content_tag(:li, class: classValue) do
      link_to title, path
    end
  end

  def title(text)
    content_tag(:div, class: "page-header") do
      content_tag(:h1) do
        text
      end
    end
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def postText(text)
    text[0..200] + "..."
  end
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Nome</label>
    <%= form.text_field :name, id: :author_name, class: 'form-control' %>
  </div>

  <div class="field">
    <label>Idade</label>
    <%= form.number_field :age, id: :author_age, class: 'form-control' %>
  </div>

  <div class="actions">
    <input name="commit" value="Enviar" data-disable-with="Enviar" type="submit">
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editando Autor</h1>

<%= render 'form', author: @author %>

<%= link_to 'Mostrar', @author %> |
<%= link_to 'Voltar', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Autores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.age %></td>
        <td><%= link_to 'Mostrar', author %></td>
        <td><%= link_to 'Editar', edit_author_path(author) %></td>
        <td><%= link_to 'Deletar', author, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Autor', new_author_path %>

app/views/authors/new.html.erb
<h1>Novo Autor</h1>

<%= render 'form', author: @author %>

<%= link_to 'Voltar', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @author.age %>
</p>

<%= link_to 'Editar', edit_author_path(@author) %> |
<%= link_to 'Voltar', authors_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :category_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Blogger</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= nav_link 'Posts', posts_path %>
        <%= nav_link 'Authors', authors_path %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger20181</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/menu' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Autor</label>
    <%= form.select :author_id, Author.all.collect {|author| [author.name , author.id]}, {}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <label>Categoria</label>
    <%= form.select :category_id, Category.all.collect {|category| [category.description , category.id]}, {}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <label>Texto</label>
    <%= form.text_area :text, id: :post_text, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Assunto</label>
    <%= form.text_field :subject, id: :post_subject, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Título</label>
    <%= form.text_field :title, id: :post_title, class: 'form-control' %>
  </div>

  <div class="actions">
    <input class="btn btn-success" name="commit" value="Enviar" data-disable-with="Enviar" type="submit">
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editando Postagem</h1>

<%= render 'form', post: @post %>

<%= link_to 'Mostrar', @post %> |
<%= link_to 'Voltar', posts_path %>

app/views/posts/homepage.html.erb
<%= title "Homepage Blogger" %>
<div class="row">
  <div class="col-xs-8">
    <% @posts.each do |post| %>
      <h2><%= post.title %></h2>
      <h3><%= post.subject %></h3>
      <p><%= postText(post.text) %></p>
      <strong>Autor: <%= post.author.name %></strong>
      <hr>
    <% end %>
  </div>
  <div class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Categorias</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% Category.all.each do |category| %>
            <li>
              <%= link_to category.description, homepage_posts_path(category_id: category.id) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Localizar</h3>
      </div>
      <div class="panel-body">
        <%= form_tag("/posts/homepage", method: "post") do %>
          <%= text_field_tag(:search_term) %>
          <%= submit_tag("Buscar") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<%= title "Postagens" %>

<table class="table">
  <thead>
    <tr>
      <th>Autor</th>
      <th>Texto</th>
      <th>Assunto</th>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.author.name %></td>
        <td><%= post.text %></td>
        <td><%= post.subject %></td>
        <td><%= post.title %></td>
        <td><%= link_to 'Mostrar', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Deletar', post, method: :delete, data: { confirm: 'Tem Certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Postagem', new_post_path %>

app/views/posts/new.html.erb
<h1>Nova Postagem</h1>

<%= render 'form', post: @post %>

<%= link_to 'Voltar', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @post.author.name %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>Assunto:</strong>
  <%= @post.subject %>
</p>

<p>
  <strong>Título:</strong>
  <%= @post.title %>
</p>

<%= link_to 'Editar', edit_post_path(@post) %> |
<%= link_to 'Voltar', posts_path %>